name: Deploy JupyterLite site
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install "jupyterlite==0.6.4" "jupyterlite-pyodide-kernel==0.6.1"
      # build to the default _output and set the base-url for GitHub Pages subpath
      - run: jupyter lite build --contents content --base-url /my-lite/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _output
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
